### ISSUE TITLE
좋아요 한사람 리스트보기 & 매칭 된 사람 리스트보기 UI 구현

### ISSUE THREAD

**Issue by wody-d** [mash-up-kr/Marryting-iOS#34]
## 작업 

- UI 구성

### 스크린샷
<img width="300" alt="스크린샷 2022-07-18 오전 2 14 07" src="https://user-images.githubusercontent.com/56102421/179417058-884b514a-2b39-4824-ae5b-dce7163c69ef.png">

**Comment by wody-d** [comment]
이 피쳐 이름을 `MyGuestList`로 하고 진행중인데 이름이 `GuestList`와 두 글자 차이라 후에 헷갈릴 것 같습니다. 

좋은 네이밍 있을까요? @gunoooo @p41155a

**Comment by gunoooo** [comment]
> 이 피쳐 이름을 `MyGuestList`로 하고 진행중인데 이름이 `GuestList`와 두 글자 차이라 후에 헷갈릴 것 같습니다. 
> 
> 좋은 네이밍 있을까요? @gunoooo @p41155a 
> 

음 딱히 떠오르는게 없네요? 이미 그렇게 진행중이면 변경하지 않고 가도 좋을거 같아요

**Comment by wody-d** [comment]
의견 감사합니다 :)

**Comment by wody-d** [comment]
## ImageVIew in CollectionView does not work contentMode

- https://stackoverflow.com/questions/28517926/uicollectionviewcell-uiimageview-ignores-contentmode-overflows-image
