### ISSUE TITLE
카드 슬라이드 애니메이션

### ISSUE THREAD

**Issue by gunoooo** [mash-up-kr/Marryting-iOS#4]
<img width="303" alt="스크린샷 2022-06-14 오후 11 03 53" src="https://user-images.githubusercontent.com/39177603/173599881-2a643aff-6761-4c4a-9b2c-099a97796905.png">

https://www.pinterest.co.kr/pin/85498092917518771/

### 검토할 사항
- 카드 중첩
- 카드 슬라이드 (상하좌우 자유롭게)

**Comment by p41155a** [comment]
건우가 [ZLSwipeableViewSwift](https://github.com/zhxnlai/ZLSwipeableViewSwift)를 추천해주어

검토하였고 필요한 기능이 있어서

demo에서 필요한 코드만을 들고 오며 demo에서 다른 라이브러리들을 사용하여 이를 제거하는 작업을 하였습니다.
